# Generated by Django 6.0.2 on 2026-02-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_orientation", "0002_orientationresult"),
        ("universities", "0002_actionhistory_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=1)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FiliereProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("R", models.IntegerField(default=0)),
                ("I", models.IntegerField(default=0)),
                ("A", models.IntegerField(default=0)),
                ("S", models.IntegerField(default=0)),
                ("E", models.IntegerField(default=0)),
                ("C", models.IntegerField(default=0)),
                (
                    "filiere",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="universities.filiere",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChoiceTraitScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_scores",
                        to="tests_orientation.choice",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests_orientation.trait",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ChoiceScore",
        ),
    ]
