# Generated by Django 6.0.2 on 2026-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_orientation", "0003_trait_filiereprofile_choicetraitscore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="question_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
