# Generated by Django 6.0.2 on 2026-02-27 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_actionhistory_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "advisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_candidatures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidature",
            name="submitted_by_advisor",
            field=models.BooleanField(default=False),
        ),
    ]
