# Generated by Django 6.0.2 on 2026-03-01 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0003_candidature_advisor_candidature_submitted_by_advisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidature",
            old_name="submitted_by_advisor",
            new_name="advisor_approved",
        ),
        migrations.RemoveField(
            model_name="candidature",
            name="reviewed_by",
        ),
        migrations.AddField(
            model_name="candidature",
            name="reviewed_by_university",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "university"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_candidatures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidature",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "advisor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisor_candidatures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="candidature",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidatures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
